config/routes.rb
Cats::Application.routes.draw do

  resources :xclubs do
    resources :xevents
  end

  resources :tags do
    resources :likes
    resources :follows
  end

  resources :lists do
    resources :comments
    resources :likes
    resources :rates
    resources :taglinks
    get ':id/page/:page', :action => :show, :on => :collection
  end

  resources :articles do
    resources :comments
    resources :likes
    resources :rates
    resources :taglinks
    resources :links
  end

  resources :videos do
    resources :comments
    resources :likes
    resources :rates
    resources :taglinks
    resources :links
  end

  resources :books do
    resources :comments
    resources :likes
    resources :rates
    resources :taglinks
    resources :links
  end
  resources :scholars
  
  resources :comments
  resources :taglinks
  resources :links

  get '/editor' => 'static_pages#markdowneditor', :as => :markdowneditor
  get '/terms' => 'static_pages#terms', :as => :terms
  get '/aboutus' => 'static_pages#aboutus', :as => :aboutus
  get '/joinus' => 'static_pages#joinus', :as => :joinus
  get '/helpme' => 'static_pages#helpme', :as => :helpme

  resources :help

  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks",:registrations => "users/registrations"}

  root 'welcome#index'
  get '/search' => 'search#index', :as => :new_search
  get '/manage' => 'help#manage', :as => :help_manage
  post '/manage' => 'help#apply', :as => :help_apply
  post '/manage/xclubadmin' => 'help#xclubadmin', :as => :help_xclubadmin
  
  post '/lists/:id/sort' => 'lists#sort', :as=> :sort

  get '/upload' => 'uploads#new', :as => :upload_form
  post '/upload' => 'uploads#create', :as => :upload

  

end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :taglinks, :as => :tagable, dependent: :destroy
  has_many :likes, :as => :likeable, dependent: :destroy
  has_many :comments, :as => :commentable, dependent: :destroy
  has_many :rates, :as => :rateable, dependent: :destroy
  has_many :links, dependent: :destroy
  serialize :links_array, Array
  mount_uploader :cover, ImageUploader
  scope :top10Booklist,->{select("lists.id, lists.title, lists.cover, count(likes.id) AS likes_count").where(list_type: 1).joins(:likes).group("lists.id").order("likes_count DESC").limit(10)}
  scope :newest3Booklist,->{select("lists.id, lists.cover, lists.title").where(list_type: 1).order("created_at desc").limit(3)}
  scope :top10Videolist,->{select("lists.id, lists.cover, lists.title, count(likes.id) AS likes_count").where(list_type: 2).joins(:likes).group("lists.id").order("likes_count DESC").limit(10)}
  scope :newest6Videolist,->{select("lists.id,lists.cover, lists.title").where(list_type: 2).order("created_at desc").limit(6)}
  scope :best6Booklist,->{select("lists.id, lists.cover, lists.title, lists.rate").where(list_type: 1).group("lists.id").order("lists.rate DESC").limit(6)}
  scope :best6Videolist,->{select("lists.id, lists.cover, lists.title, lists.rate").where(list_type: 2).group("lists.id").order("lists.rate DESC").limit(6)}
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]

  load_and_authorize_resource

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @commentable = @list
    @comments = @commentable.comments
    @comment = Comment.new
    @likeable = @list
    @likes = @likeable.likes
    @like = Like.new
    @rateable = @list
    @rates = @rateable.rates
    @rate = Rate.new
    @taglinkable = @list
    @taglinks = @taglinkable.taglinks
    @taglink = Taglink.new
    @tags = Tag.all

    @type = @list[:list_type]
    if @type == BOOKLIST
      @best = List.best6Booklist
    elsif @type == VIDEOLIST
      @best = List.best6Videolist
    end

    @Link = Link
    if (@list.links.length != @list.links_array.length)
    	@links_array = []
    	@list.links.each do |link|
    		@links_array.push link.id
    	end
    else
    	@links_array = @list.links_array
    end
    @links_array = Kaminari.paginate_array(@links_array).page(params[:page]).per(5)
#    @links = Link.find(@list.links_array)
  end

  # GET /lists/new
  def new
    @types =[["书单",BOOKLIST],["视频集",VIDEOLIST],["经验贴集",ARTICLELIST],["综合集",MIXLIST]]
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
    @types =[["书单",BOOKLIST],["视频集",VIDEOLIST],["经验贴集",ARTICLELIST],["综合集",MIXLIST]]
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)
    @list[:user_id] = current_user.id
    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: '新建集合成功' }
        format.json { render action: 'show', status: :created, location: @list }
      else
        format.html { render action: 'new' }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    @list= List.find(params[:id])

    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: '修改集合成功' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy

    # redirect to different page according to list type
    @redirect = "#"
    @type = @list[:list_type]
    puts @type
    if @type == BOOKLIST
      @redirect = books_path
    elsif @type == VIDEOLIST
      @redirect = videos_path
    elsif @type == ARTICLELIST
      @redirect = articles_path
    else
      @redirect = root_path
    end

    respond_to do |format|
      format.html { redirect_to @redirect, notice: '删除集合成功' }
      format.json { head :no_content }
    end
  end

  def sort
    list= List.find(params[:id])
    list.links_array= params[:lkarray]
	  list.save
    respond_to do |format|
      format.html { redirect_to lists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:title, :summary, :list_type, :cover)
    end
    

end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    标题：
    <%= f.text_field :title %>
  </div>
  <div class="field">
    类型：
    <%= f.select :list_type, @types %>
  </div>
  <div class="field">
    封面：
    <%= image_tag(@list.cover.url("medium")) if @list.cover? %>
    <%= f.file_field :cover %>
  </div>
  <div class="field">
    描述：
    <%= f.text_area :summary %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/_recommendbooklist.html.erb
<aside class="col-sm-4">
  <section class="wm-recommend">
    <h3 class="page-header">
      <span class="glyphicon glyphicon-plus-sign"></span> 推荐书单
      <a class="wm-quick-link" href="/search?list=book">查看全部</a>
    </h3>
    <div class="row">
      <% @best.each do |recommend| %>
          <figure class="col-xs-6">
            <a class="thumbnail" href="/lists/<%= recommend.id %>.html">
              <img src="<%= recommend.cover %>!medium" alt="" title="<%= recommend.title %>"/>
            </a>
            <figcaption>
              <a href="/lists/<%= recommend.id %>.html" title="<%= recommend.title %>"><%= recommend.title %></a>
            </figcaption>
          </figure>
      <% end %>
    </div>
  </section>
</aside>

app/views/lists/_recommendvideolist.html.erb
<aside class="col-sm-4">
  <section class="wm-recommend">
    <h3 class="page-header">
      <span class="glyphicon glyphicon-plus-sign"></span> 推荐视频集
      <a class="wm-quick-link" href="/search?list=video">查看全部</a>
    </h3>
    <div class="row">
      <% @best.each do |recommend| %>
          <figure class="col-xs-6">
            <a class="thumbnail" href="/lists/<%= recommend.id %>.html">
              <img src="<%= recommend.cover %>!medium" alt="" title="<%= recommend.title %>"/>
            </a>
            <figcaption>
              <a href="/lists/<%= recommend.id %>.html" title="<%= recommend.title %>"><%= recommend.title %></a>
            </figcaption>
          </figure>
      <% end %>
    </div>
  </section>
</aside>

app/views/lists/edit.html.erb
<h1>编辑集合</h1>

<%= render 'form' %>

<%= link_to '显示', @list %>

app/views/lists/index.html.erb
<h1>Listing lists</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Summary</th>
      <th>Creator</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.title %></td>
        <td><%= list.summary %></td>
        <td><%= list.user[:name] %></td>
        <td><%= link_to '显示', list %></td>
        <td><%= link_to '编辑', edit_list_path(list) %></td>
        <td><%= link_to '删除', list, method: :delete, data: { confirm: '请再次确认删除' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新建集合', new_list_path %>

app/views/lists/new.html.erb
<h1>新建集合</h1>

<%= render 'form' %>

<%= link_to '返回', lists_path %>

app/views/lists/show.html.erb
<% content_for :head do %>
   <title><%= @list.title %> | 万门大学</title>
<% end %>

<main class="container" role="main">
  <article class="col-sm-8">
    <h3 class="page-header">
      <span class="wm-title"><%= @list.title %></span>
      <span class="wm-quick-link">
        <% if can? :edit, @list %>
        <a href="/lists/<%=@list.id %>/edit">修改</a> |
        <a href="#" class="sort-trigger">排序</a> |
        <% end %>
        <a href="JavaScript:window.history.back();">返回</a>
        <% if can? :destroy, @list %>
          | <%= link_to '删除', list_path(@list), method: :delete, data: { confirm: '请确认要删除此集合?' } %>
        <% end %>
      </span>
    </h3>
    <p class="wm-pub-metadata">
      <span style="color:#5bc0de"><%= @list.user[:name] %></span> 发布于
      <%= @list[:updated_at].strftime('%b %d, %Y %H:%M')  %>
      <span class="pull-right"><%= @list.taglinks.length %> 个标签 | <%= @list.likes.length %>人喜欢 | <%= @list.comments.length%>个评论</span>
    </p>
    <section class="wm-indent">  
      <%=raw Kramdown::Document.new(@list.summary).to_html%>
    </section>
    <section class="wm-book-list wm-book-gallery">
      <% @links_array.each do |lkid| %>
      	<% link=@Link.find(lkid) %> <!--TODO:: fix this proformance issue -->
      <div lkid="lkarray-<%= link.id %>">
        <div class="row wm-list-item">
          <figure class="col-sm-3 col-xs-6">
                <% case link.linkable.class.name
                    when 'Book'%>          
                    <a href="/books/<%=link.linkable.id %>.html" class="thumbnail">
                      <img src="<%= link.linkable.cover %>!medium" alt="" title="<%=link.linkable.title%>">
                    </a>
                 <% when 'Video'%>
                    <a href="/videos/<%=link.linkable.id %>.html" class="thumbnail">
                      <img src="<%= link.linkable.cover %>!medium" alt="" title="<%=link.linkable.title%>">
                    </a>
                 <% when 'Article' %>
                    <a href="/articles/<%=link.linkable.id %>.html">
                      <%=link.linkable.title%>
                    </a>
                <%  end %>
          </figure>
          <div class="col-sm-9">
            <h4> 
                <% case link.linkable.class.name
                    when 'Book'%>
                        <a href=" /books/<%=link.linkable.id %>.html"><%=link.linkable.title%></a>
                 <% when 'Video'%>
                        <a href=" /videos/<%=link.linkable.id %>.html"><%=link.linkable.title%></a>
                 <% when 'Article' %>
                        <a href=" /articles/<%=link.linkable.id %>.html"><%=link.linkable.title%></a>
                <%  end %>
            </h4>
            <span>
                <% case link.linkable.class.name
                    when 'Book'%>
                        作者: <%= link.linkable.author %>
                <% when 'Video'%>
                        主讲人: <%= link.linkable.lecturer %>
                <% when 'Article' %>
                        创建者: <%= link.linkable.author %>
                <%  end %>
            </span>
            <p>
              <%= link.description %>
            </p>
           
           <% if current_user&& current_user[:role]>=SCHOLAR %> <p> <a href="/links/<%= link.id%>/edit">修改描述</a></p>
           <% end %>
          </div>
        </div>
        <hr/>
      </div>
      <% end %>
    </section>
    <%= paginate @links_array %>
    <section class="wm-metadata">
      <div>   
      <%= render :partial => 'taglinks/taglinks' %>
      <%= render :partial => 'taglinks/form' %>
      <%= render :partial => 'likes/likes' %>
      <%= render :partial => 'likes/form' %>
      <%= render :partial => 'rates/rates' %>
      <%= render :partial => 'rates/form' %> 
      </div>
    </section>

    <hr/>
    <%= render :partial => 'comments/shares' %>    
    <%= render :partial => 'comments/comments' %>
    <%= render :partial => 'comments/form' %>
  </article>
  <% if @type == BOOKLIST %>
    <%= render :partial => 'lists/recommendbooklist' %>
  <% elsif @type == VIDEOLIST %>
    <%= render :partial => 'lists/recommendvideolist' %>
  <% end %>
      </main>

<% content_for :bottom_script do %>
    <%= render :partial => 'layouts/markdown' %>
    <%= render :partial => 'layouts/raty' %>
    <%= render :partial => 'layouts/rails' %>

    <script type="text/javascript">
      var initSortable = function(thelist){
        $(thelist).sortable({'axis':'y'});
        $(thelist).sortable('enable');
      }
      var sortableToArray = function(thelist, targetAttr){
        var tmpArray = $(thelist).sortable('toArray',{'attribute': targetAttr});
        return tmpArray;
      }
      var sortableSerialize = function(thelist, targetAttr){
        var tmpArray = $(thelist).sortable('serialize',{'attribute': targetAttr});
        return tmpArray;
      }
      var disableSortable = function(thelist){
        $(thelist).sortable('disable');
      }
      var enableSortable = function(thelist){
        $(thelist).sortable('enable');
      }
      var triggerIsClicked = function(thetrigger, thelist){
        initSortable(thelist);
        $(thetrigger).text('停止排序');
        $(thetrigger).unbind()
        $(thetrigger).bind('click',function(){
          $(thetrigger).text('排序');
          $.post('./<%= @list.id %>/sort',sortableSerialize(thelist,'lkid'));
          disableSortable(thelist);
          $(thetrigger).unbind();
          $(thetrigger).bind('click',function(){triggerIsClicked(thetrigger,thelist);})
        });
      }
      $('.sort-trigger').bind('click',function(){
        triggerIsClicked('.sort-trigger', '.wm-book-list');
      })
    </script>
<% end %>