config/routes.rb
Cats::Application.routes.draw do

  resources :xclubs do
    resources :xevents
  end

  resources :tags do
    resources :likes
    resources :follows
  end

  resources :lists do
    resources :comments
    resources :likes
    resources :rates
    resources :taglinks
    get ':id/page/:page', :action => :show, :on => :collection
  end

  resources :articles do
    resources :comments
    resources :likes
    resources :rates
    resources :taglinks
    resources :links
  end

  resources :videos do
    resources :comments
    resources :likes
    resources :rates
    resources :taglinks
    resources :links
  end

  resources :books do
    resources :comments
    resources :likes
    resources :rates
    resources :taglinks
    resources :links
  end
  resources :scholars
  
  resources :comments
  resources :taglinks
  resources :links

  get '/editor' => 'static_pages#markdowneditor', :as => :markdowneditor
  get '/terms' => 'static_pages#terms', :as => :terms
  get '/aboutus' => 'static_pages#aboutus', :as => :aboutus
  get '/joinus' => 'static_pages#joinus', :as => :joinus
  get '/helpme' => 'static_pages#helpme', :as => :helpme

  resources :help

  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks",:registrations => "users/registrations"}

  root 'welcome#index'
  get '/search' => 'search#index', :as => :new_search
  get '/manage' => 'help#manage', :as => :help_manage
  post '/manage' => 'help#apply', :as => :help_apply
  post '/manage/xclubadmin' => 'help#xclubadmin', :as => :help_xclubadmin
  
  post '/lists/:id/sort' => 'lists#sort', :as=> :sort

  get '/upload' => 'uploads#new', :as => :upload_form
  post '/upload' => 'uploads#create', :as => :upload

  

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :likes, :as => :likeable, dependent: :destroy
	has_many :taglinks, :as => :tagable, dependent: :destroy
	has_many :rates, :as => :rateable, dependent: :destroy
	has_many :comments, :as => :commentable, dependent: :destroy
	has_many :links, :as => :linkable, dependent: :destroy
	belongs_to :user
  scope :best6, ->{ select("articles.id, articles.title, articles.summary, articles.user_id, articles.updated_at, articles.rate").group("articles.id").order("articles.rate DESC").limit(6)}
  scope :newest10, ->{ select("articles.id,articles.title").order("created_at desc").limit(10)}
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]

  load_and_authorize_resource

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
    @best6 = Article.best6
    @newest10 = Article.newest10
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @commentable = @article
    @comments = @commentable.comments
    @comment = Comment.new
    @likeable = @article
    @likes = @likeable.likes
    @like = Like.new
    @rateable = @article
    @rates = @rateable.rates
    @rate = Rate.new
    @taglinkable = @article
    @taglinks = @taglinkable.taglinks
    @taglink = Taglink.new
    @linkable = @article
    @links = @linkable.links
    @link = Link.new
    @best = Article.best6
    if (current_user)
      @lists = List.where("user_id = ? AND (list_type = ? OR list_type = ?)", current_user[:id], ARTICLELIST, MIXLIST)
    else
      @lists = []
    end
    @tags = Tag.all
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article[:user_id] = current_user.id
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: '您已成功添加新的经验贴' }
        format.json { render action: 'show', status: :created, location: @article }
      else
        format.html { render action: 'new', notice: '添加经验贴失败' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: '您已成功修改经验贴' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: '成功删除经验贴' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :summary, :content, :url, :author).merge(user_id: current_user.id)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for @article, html: {class: "container form-horizontal wm-form", role: "form"} do |f| %>
  <div class="col-sm-10">
      <% if @article.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

          <ul>
          <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.label "标题*", :class=>"col-sm-3", :for=>"article_title" %>
        <%= f.text_field :title, :class=>"form-control", :placeholder=>"请输入经验贴标题(必填)", :title=>"请输入经验贴标题(必填)", :required=>true %>
      </div>
      <div class="form-group">
        <%= f.label "作者*", :class=>"col-sm-3", :for=>"article_author" %>
        <%= f.text_field :author, :class=>"form-control", :placeholder=>"请输入经验贴作者(必填)", :title=>"请输入经验贴作者(必填)", :required=>true %>
      </div>
      <div class="form-group">
        <%= f.label "链接", :class=>"col-sm-3", :for=>"article_url" %>
        <%= f.text_field :url, :type=>"url", :class=>"form-control", :placeholder=>"请输入经验贴链接URL", :title=>"请输入经验贴链接URL" %>
      </div>
      <div class="form-group">
        <%= f.label "摘要", :class=>"col-sm-3", :for=>"article_summary" %>
        <div class="col-sm-9 wm-reset">
        <%= f.text_area :summary, :rows=>"5", :class=>"form-control", :placeholder=>"请输入经验贴摘要(100字以内)", :title=>"请输入经验贴摘要(100字以内)" %>
      	</div>
      </div>
      <div class="form-group">
      	<%= f.label "内容*", :class=>"col-sm-3", :for=>"article_content" %>
          <div class="col-sm-9 wm-reset">
              <a class="btn btn-primary btn-sm pull-right" href="/editor">如何编辑？</a>
              <br/>
              <div class="wmd-panel">
                  <div id="wmd-button-bar"></div>
                  <%= f.text_area :content,:id=>"wmd-input", :class=>"wmd-input", :placeholder=>"请在此编辑经验贴正文", :title=>"请在此编辑经验贴正文", :required=>true %>
              </div>
              <div class="wmd-panel wmd-preview" id="wmd-preview"></div>
          </div>
      </div>
      <div class="form-group">
        <button class="btn btn-primary pull-right" type="submit">完成</button>
      </div>
  </div>
<% end %>

app/views/articles/_recommend.html.erb
<aside class="col-sm-4">
  <section class="wm-recommend">
    <h3 class="page-header">
      <span class="glyphicon glyphicon-plus-sign"></span> 推荐经验贴
      <a class="wm-quick-link" href="">查看全部</a>
    </h3>
  <ul>
  <% @best.each do |recommend| %>
    <li><a href="/articles/<%=recommend.id %>.html" title="<%= recommend.title %>"><%= recommend.title %></a></li>
  <% end %>
  </ul>
  </section>
</aside>

app/views/articles/edit.html.erb
<% content_for :head do %>
   <title>编辑经验帖 | 万门大学</title>
<% end %>

<main class="container" role="main">
  <h3 class="page-header text-center">
    <span class="wm-title">编辑经验贴</span>
    <span class="wm-quick-link">
      <%= link_to '显示', @article %> |
      <%= link_to '返回', articles_path %>
      <a href="JavaScript:window.history.back();">返回(浏览器)</a>
    </span>
  </h3>
  <%= render 'form' %>
</main>

<% content_for :bottom_script do %>
    <%= render :partial => 'layouts/markdown' %>
<% end %>

app/views/articles/index.html.erb
<% content_for :head do %>
   <title>经验贴 | 万门大学</title>
<% end %>

<main class="container" role="main">
  <article class="col-sm-8">
    <h3 class="page-header">
      <span class="glyphicon glyphicon-calendar"></span> 推荐经验贴
      <a class="wm-quick-link" href="/search?type=article&sortby=rate">查看全部</a>
    </h3>
    <section class="wm-article-list">
      <% @best6.each do |article| %>
      <div>
        <h4><a href="/articles/<%= article.id %>.html"><%= article.title %></a></h4>
        <p class="wm-pub-metadata">
          <%= article.user[:name] %> 发布于 <%= article.updated_at.strftime('%b %d, %Y %H:%M') %>
          <span class="pull-right"><%= article.taglinks.length %>个标签 | <%= article.links.length %>个集合 | <%= article.likes.length %>人喜欢 | <%= article.comments.length %>个评论</span>
        </p>
        <p><%= article.summary %><a href="/articles/<%= article.id %>.html">继续阅读</a>
        </p>
      </div>
      <hr/>
      <% end %>
    </section>

    <!--
    <section class="text-center">
     <ul class="pagination">
       <li class="disabled"><a href="上一页">&laquo;</a></li>
       <li class="active"><a href="#">1</a></li>
       <li><a href="#">2</a></li>
       <li><a href="#">3</a></li>
       <li><a href="#">4</a></li>
       <li><a href="#">5</a></li>
       <li><a href="#">6</a></li>
       <li><a href="#">7</a></li>
       <li><a href="#">8</a></li>
       <li><a href="#">9</a></li>
       <li><a href="#">10</a></li>
       <li><a href="#" title="下一页">&raquo;</a></li>
     </ul>
    </section>
    -->
  </article>

  <aside class="col-sm-4">
    <section>
      <h3 class="page-header">
        <span class="glyphicon glyphicon-tasks"></span> 最新经验贴
        <a class="wm-quick-link" href="/search?type=article">查看全部</a>
      </h3>
      <ol class="wm-list-popular">
        <% @newest10.each do |a| %>
            <li><a href="/articles/<%=a.id %>.html"><%=a.title %></a></li>
        <% end %>
      </ol>
    </section>

    <!--
    <section>
      <h3 class="page-header">
        <span class="glyphicon glyphicon-stats"></span> 热门标签
        <a class="wm-quick-link" href="">查看全部</a>
      </h3>
      <div class="wm-tags-popular">
        【<a class="wm-tag-category" href="">物理</a>】
        <a href="">牛顿力学</a> |
        <a href="">统计物理</a> |
        <a href="">量子场论</a>
      </div>
      <div class="wm-tags-popular">
        【<a class="wm-tag-category" href="">计算机</a>】
        <a href="">编程</a> |
        <a href="">机器学习</a> |
        <a href="">网页设计</a>
      </div>
      <div class="wm-tags-popular">
        【<a class="wm-tag-category" href="">数学</a>】
        <a href="">微积分</a> |
        <a href="">线性代数</a> |
        <a href="">数学物理方程</a>
      </div>
      <div class="wm-tags-popular">
        【<a class="wm-tag-category" href="">外国语</a>】
        <a href="">英语</a> |
        <a href="">法语</a> |
        <a href="">希伯来语</a>
      </div>
      <div class="wm-tags-popular">
        【<a class="wm-tag-category" href="">文学</a>】
        <a href="">中国古典文学</a> |
        <a href="">文学史</a> |
        <a href="">希腊文学</a>
      </div>
    </section>
    -->
  </aside>
</main>

app/views/articles/new.html.erb
<% content_for :head do %>
   <title>添加经验帖 | 万门大学</title>
<% end %>

<main class="container" role="main">
  <h3 class="page-header text-center">
    <span class="wm-title">添加经验贴</span>
    <span class="wm-quick-link">
      <a href="JavaScript:window.history.back();">返回</a>
    </span>
  </h3>
  <%= render 'form' %>
</main>

<% content_for :bottom_script do %>
    <%= render :partial => 'layouts/markdown' %>
<% end %>

app/views/articles/show.html.erb
<% content_for :head do %>
   <title><%= @article.title %> | 万门大学</title>
<% end %>

<main class="container" role="main">
<article class="col-sm-8">
    <h3 class="page-header">
        <span class="wm-title">
            <%= @article.title %>
        </span>
        <span class="wm-quick-link">
            <% if can? :edit, @article %>
                <%= link_to '修改', edit_article_path(@article) %>  |
            <% end %>
            <%= link_to '返回', articles_path %>
            <% if can? :destroy, @article %>
                | <%= link_to '删除', article_path(@article), method: :delete, data: { confirm: '请确认要删除此经验贴?' } %>
            <% end %>
        </span>
    </h3>
    <p class="wm-pub-metadata">
        <span><%= @article.user[:name] %></span> 发布于 <%= @article[:updated_at].strftime('%b %d, %Y %H:%M')  %>
        <span class="pull-right"><%= @taglinks.length %>个标签 | <%= @links.length %>个单子 | <%= @likes.length %>人喜欢 | <%= @comments.length %>条评论</span>
    </p>

    <section class="wm-indent">
     摘要: <%= @article.summary%>
    </section>
    <section class="wm-indent">
     正文: <%=raw Kramdown::Document.new(@article.content).to_html%>
    </section>

    <section class="wm-metadata">
        <div>
            <span>标签</span>
            <%= render :partial => 'taglinks/taglinks' %>
            <%= render :partial => 'taglinks/form' %>
            <br/>
            <span>单子</span>
            <%= render :partial => 'links/links' %>
            <%= render :partial => 'links/form' %>
            <br/>
            <span>评分</span>
            <%= render :partial => 'rates/rates' %>
            <%= render :partial => 'rates/form' %>

            <%= render :partial => 'likes/form' %>
        </div>
    </section>
    <hr/>
    <%= render :partial => 'comments/shares' %>  
    <%= render :partial => 'comments/comments' %>
    <hr/>
    <%= render :partial => 'comments/form' %>
  </article>
  <%= render :partial => 'articles/recommend' %>
</main>

<% content_for :bottom_script do %>
    <%= render :partial => 'layouts/markdown' %>
    <%= render :partial => 'layouts/raty' %>
    <%= render :partial => 'layouts/rails' %>
<% end %>