config/routes.rb
Cats::Application.routes.draw do

  resources :xclubs do
    resources :xevents
  end

  resources :tags do
    resources :likes
    resources :follows
  end

  resources :lists do
    resources :comments
    resources :likes
    resources :rates
    resources :taglinks
    get ':id/page/:page', :action => :show, :on => :collection
  end

  resources :articles do
    resources :comments
    resources :likes
    resources :rates
    resources :taglinks
    resources :links
  end

  resources :videos do
    resources :comments
    resources :likes
    resources :rates
    resources :taglinks
    resources :links
  end

  resources :books do
    resources :comments
    resources :likes
    resources :rates
    resources :taglinks
    resources :links
  end
  resources :scholars
  
  resources :comments
  resources :taglinks
  resources :links

  get '/editor' => 'static_pages#markdowneditor', :as => :markdowneditor
  get '/terms' => 'static_pages#terms', :as => :terms
  get '/aboutus' => 'static_pages#aboutus', :as => :aboutus
  get '/joinus' => 'static_pages#joinus', :as => :joinus
  get '/helpme' => 'static_pages#helpme', :as => :helpme

  resources :help

  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks",:registrations => "users/registrations"}

  root 'welcome#index'
  get '/search' => 'search#index', :as => :new_search
  get '/manage' => 'help#manage', :as => :help_manage
  post '/manage' => 'help#apply', :as => :help_apply
  post '/manage/xclubadmin' => 'help#xclubadmin', :as => :help_xclubadmin
  
  post '/lists/:id/sort' => 'lists#sort', :as=> :sort

  get '/upload' => 'uploads#new', :as => :upload_form
  post '/upload' => 'uploads#create', :as => :upload

  

end

app/models/xclub.rb
class Xclub < ActiveRecord::Base
  has_many :xevents, as: :xeventable, dependent: :destroy
  mount_uploader :thumbnail, ImageUploader
end

app/controllers/xclubs_controller.rb
class XclubsController < ApplicationController
  before_action :set_xclub, only: [:show, :edit, :update, :destroy]

  load_and_authorize_resource

  # GET /xclubs
  # GET /xclubs.json
  def index
    @xclubs = Xclub.all
    @latest = Xevent.latest5
  end

  # GET /xclubs/1
  # GET /xclubs/1.json
  def show
    # get the latest 3 event of the current xclub
    @latest = Xevent.where("xclub_id = ?", @xclub.id).order("created_at DESC").limit(3)
  end

  # GET /xclubs/new
  def new
    @xclub = Xclub.new
  end

  # GET /xclubs/1/edit
  def edit
  end

  # POST /xclubs
  # POST /xclubs.json
  def create
    @xclub = Xclub.new(xclub_params)

    respond_to do |format|
      if @xclub.save
        format.html { redirect_to @xclub, notice: 'Xclub was successfully created.' }
        format.json { render action: 'show', status: :created, location: @xclub }
      else
        format.html { render action: 'new' }
        format.json { render json: @xclub.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /xclubs/1
  # PATCH/PUT /xclubs/1.json
  def update
    respond_to do |format|
      if @xclub.update(xclub_params)
        format.html { redirect_to @xclub, notice: 'Xclub was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @xclub.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /xclubs/1
  # DELETE /xclubs/1.json
  def destroy
    @xclub.destroy
    respond_to do |format|
      format.html { redirect_to xclubs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_xclub
      @xclub = Xclub.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def xclub_params
      params.require(:xclub).permit(:name, :started, :summary, :thumbnail)
    end

    #
    def transform_date(date)
      puts date
      date[4] = '年'
      date[7] = '月'
      date << '日'
      date
    end

  helper_method :transform_date
end

app/helpers/xclubs_helper.rb
module XclubsHelper
end

app/views/xclubs/_form.html.erb
<%= form_for @xclub, :html =>{:class =>"container form-horizontal wm-form", :role =>"form", :multipart => true} do |f| %>
<div class="col-sm-10">
  <div class="form-group">
    <label class="col-sm-3" for="xclub_thumbnail">头像*</label>
    <%= image_tag(@xclub.thumbnail.url("medium")) if @xclub.thumbnail? %>
    <%= f.file_field :thumbnail, required: :true %>
  </div>
  <div class="form-group">
    <label class="col-sm-3" for="xclub_name">社团名称*</label>
    <%= f.text_field :name, class: :'form-control', placeholder: :'请输入社团名称(必填)', required: :true %>
  </div>
  <div class="form-group">
    <label class="col-sm-3" for="xclub_started">建立时间*</label>
    <%= f.date_select :started, class: :'form-control' %>
  </div>
  <div class="form-group">
    <label class="col-sm-3" for="xclub_summary">社团简介*</label>
    <%= f.text_field :summary, class: :'col-sm-offset-1 form-control', placeholder: :'请输入社团简介(必填)', required: :true %>
  </div>

  <div class="text-center">
    <button class="col-sm-offset-5 btn btn-primary" type="submit">完成</button>
  </div>
</div>
<% end %>

app/views/xclubs/edit.html.erb
<h1>Editing xclub</h1>

<%= render 'form' %>

<%= link_to 'Show', @xclub %> |
<%= link_to 'Back', xclubs_path %>

app/views/xclubs/index.html.erb
<% content_for :head do %>
    <title> 万门大学X | 万门大学</title>
<% end %>

<main class="container" role="main">
  <article class="col-sm-9 wm-skip-top">
    <section class="media well">
      <img class="pull-left media-object" src="<%= asset_path "projects/wanmenX.png" %>" height="50" alt=""/>
      <div class="media-body">
        <h3 class="media-heading text-primary">万门大学X</h3>
        <p>“万门大学X”是一个以在校大学生为主要受众，以各个高校为单位，以有规划性的共同学习、讨论、分享为宗旨，以通过倡导学生自身的改变而改善中国高校学习环境为目标的全国性青年发展团体。“X”指的独立于万门大学总部运作，在申请及认证通过后，社团可自行负责组织的运营与管理以及具体活动形式和主题的设计工作。</p>
      </div>
    </section>

    <section class="wm-gallery">
      <h3 class="page-header">
        <span class="glyphicon glyphicon-star"></span> 精选活动
      </h3>
      <div class="row wm-activity">

      </div>
      <div class="row wm-activity">

      </div>
    </section>
  </article>

  <aside class="col-sm-3">
    <section class="wm-recent-news">
      <h3 class="page-header">
        <span class="glyphicon glyphicon-calendar"></span> 近期动态
        <!-- <a class="wm-quick-link" href="">查看全部</a> -->
      </h3>
      <ul>
        <% @latest.each do |event| %>
            <li><%= event.time.to_date %>
              <a href="<%=xclub_xevent_path(event[:xclub_id], event)%>"><h5><%= event.title %></h5></a>
              <span><%= event.location %></span>
            </li>
        <% end %>
      </ul>
    </section>
    <section class="wm-member-list">
      <h3 class="page-header">
        <span class="glyphicon glyphicon-flag"></span> 成员风采
        <!-- <a class="wm-quick-link" href="">查看全部</a> -->
      </h3>
      <% @xclubs.each do |xclub| %>
          <div>
            <%=image_tag(xclub.thumbnail.url("medium"), class: :"img-rounded", height: :"50", alt: :"")%>
            <a href="/xclubs/<%= xclub.id %>" title=""<%= xclub.name %>"><%= xclub.name %></a> <br>
          </div>
      <% end %>
    </section>
  </aside>

<br>

</main>

<% content_for :bottom_script do %>
    <%= render :partial => 'layouts/raty' %>
    <%= render :partial => 'layouts/rails' %>
<% end %>

app/views/xclubs/new.html.erb
<% content_for :head do %>
    <title>新建X社团 | 万门大学</title>
<% end %>

<main class="container" role="main">
  <h3 class="page-header text-center">
    <span class="wm-title">新建X社团</span>
    <span class="wm-quick-link">
      <a href="JavaScript:window.history.back();">返回</a>
    </span>
  </h3>
  <%= render 'form' %>
</main>

<% content_for :bottom_script do %>
    <%= render :partial => 'layouts/markdown' %>
<% end %>

app/views/xclubs/show.html.erb
<% content_for :head do %>
    <title> X社团 | 万门大学</title>
<% end %>

<main class="container" role="main">
  <aside class="col-sm-3 text-center wm-member-info">
    <section>
      <h3><%= @xclub.name %></h3>
      <%=image_tag(@xclub.thumbnail.url("medium"), class: :"img-rounded", alt: :"")%>
      <ul class="nav nav-pills nav-stacked wm-list-group">
        <li class="wm-list-group-item"><a href="">加入我们</a></li>
        <li class="wm-list-group-item"><a href="">关于我们</a></li>
        <li><a href="">联系我们</a></li>
        <% if can? :edit, @xclub %>
          <li><%= link_to '添加新活动', new_xclub_xevent_path(@xclub) %></li>
        <% end %>
        <% if can? :destroy, @xclub %>
          <li><%= link_to '删除本社团', xclub_path(@xclub), method: :delete, data: { confirm: '确定要删除此社团？(操作不可逆)' } %></li>
        <% end %>
      </ul>
    </section>
  </aside>

  <article class="col-sm-9">
    <section class="wm-recent-events">
      <h3 class="page-header">
        <span class="glyphicon glyphicon-calendar"></span> 近期动态
        <!-- <a class="wm-quick-link" href="">查看全部</a> -->
      </h3>
      <% @latest.each do |event| %>
      <div class="container">
        <div class="col-sm-3 text-right">
          <span class="text-primary"><%= transform_date(event.time.to_date.to_s) %></span><br/>
          <span class="text-primary"><%=event.time.strftime("%H:%M")%></span>
        </div>
        <div class="col-sm-6">
          <span><%= event.title %></span><br/>
          <span class="text-muted"><%= event.location %></span>
        </div>
        <div class="col-sm-3 text-center wm-md-top">
          <% if event.time > DateTime.now %>
            <span class="text-success">敬请期待</span>
          <% else %>
            <span class="text-danger">已结束</span>
          <% end %>
        </div>
      </div>
      <% end %>
    </section>

    <section class="wm-gallery">
      <h3 class="page-header">
        <span class="glyphicon glyphicon-lock"></span> 往期活动
      </h3>
      <div class="row wm-activity">
        <div class="col-sm-4">
          <div class="thumbnail">
            <a href="">
              <img src="<%= asset_path "wanmenX/x1.png" %>" alt="" title="万门谈——信仰与文化"/>
            </a>
            <h5>万门谈——信仰与文化</h5>
            <a href=""><%=@xclub.name%></a><br/>
            <span>时间：2013-07-27 09:00</span><br/>
            <span>地点：北京海淀区中关村科学院南</span>
          </div>
        </div>
      </div>
    </section>
  </article>
</main>

<% content_for :bottom_script do %>
    <%= render :partial => 'layouts/rails' %>
    <script type="text/javascript">

        $('.wm-list-group-item').on('click',function(e){
            var previous = $(this).closest(".wm-list-group").children(".active");
            previous.removeClass('active'); // previous list-item
            $(e.target).addClass('active'); // activated list-item
        });

    </script>
<% end %>