config/routes.rb
Cats::Application.routes.draw do

  resources :xclubs do
    resources :xevents
  end

  resources :tags do
    resources :likes
    resources :follows
  end

  resources :lists do
    resources :comments
    resources :likes
    resources :rates
    resources :taglinks
    get ':id/page/:page', :action => :show, :on => :collection
  end

  resources :articles do
    resources :comments
    resources :likes
    resources :rates
    resources :taglinks
    resources :links
  end

  resources :videos do
    resources :comments
    resources :likes
    resources :rates
    resources :taglinks
    resources :links
  end

  resources :books do
    resources :comments
    resources :likes
    resources :rates
    resources :taglinks
    resources :links
  end
  resources :scholars
  
  resources :comments
  resources :taglinks
  resources :links

  get '/editor' => 'static_pages#markdowneditor', :as => :markdowneditor
  get '/terms' => 'static_pages#terms', :as => :terms
  get '/aboutus' => 'static_pages#aboutus', :as => :aboutus
  get '/joinus' => 'static_pages#joinus', :as => :joinus
  get '/helpme' => 'static_pages#helpme', :as => :helpme

  resources :help

  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks",:registrations => "users/registrations"}

  root 'welcome#index'
  get '/search' => 'search#index', :as => :new_search
  get '/manage' => 'help#manage', :as => :help_manage
  post '/manage' => 'help#apply', :as => :help_apply
  post '/manage/xclubadmin' => 'help#xclubadmin', :as => :help_xclubadmin
  
  post '/lists/:id/sort' => 'lists#sort', :as=> :sort

  get '/upload' => 'uploads#new', :as => :upload_form
  post '/upload' => 'uploads#create', :as => :upload

  

end

app/models/video.rb
class Video < ActiveRecord::Base
	has_many :likes, :as => :likeable, dependent: :destroy
	has_many :taglinks, :as => :tagable, dependent: :destroy
	has_many :rates, :as => :rateable, dependent: :destroy
	has_many :comments, :as => :commentable, dependent: :destroy
	has_many :links, :as => :linkable, dependent: :destroy
	belongs_to :user
	mount_uploader :cover, ImageUploader
	scope :top10, -> {select("videos.id, videos.title, count(likes.id) AS likes_count").joins(:likes).group("videos.id").order("likes_count DESC").limit(10)}
    scope :newest6, -> {select("videos.*").order("created_at desc").limit(6)}
    scope :best6, -> {select("videos.id, videos.title, videos.cover, videos.rate").group("videos.id").order("videos.rate DESC").limit(6)}
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]

  load_and_authorize_resource

  # GET /videos
  # GET /videos.json
  def index
    @newest = Video.newest6
    @popular = Video.top10
    @best = Video.best6
    @popularVideolist = List.top10Videolist
    @bestVideolist = List.best6Videolist
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @commentable = @video
    @comments = @commentable.comments
    @comment = Comment.new
    @likeable = @video
    @likes = @likeable.likes
    @like = Like.new
    @rateable = @video
    @rates = @rateable.rates
    @rate = Rate.new
    @taglinkable = @video
    @taglinks = @taglinkable.taglinks
    @taglink = Taglink.new
    @linkable = @video
    @links = @linkable.links
    @link = Link.new
    @best = Video.best6
    if (current_user)
      @lists = List.where("user_id = ? AND (list_type = ? OR list_type = ?)", current_user[:id], VIDEOLIST, MIXLIST)
    else
      @lists = []
    end
    @tags = Tag.all
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit

  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)
    @video[:user_id] = current_user.id
    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: '添加视频成功' }
        format.json { render action: 'show', status: :created, location: @video }
      else
        format.html { render action: 'new' }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: '修改视频成功' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: '删除视频成功' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:title, :cover, :summary, :url, :lecturer).merge(user_id: current_user.id)
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>
      <ul>
      <% @video.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label "封面", :class=>"col-sm-3", :for=>"video_title" %>
    <%= image_tag(@video.cover.url("medium")) if @video.cover? %>
    <%= f.file_field :cover %>
  </div>
  <div class="form-group">
    <%= f.label "标题", :class=>"col-sm-3", :for=>"video_title" %>
    <%= f.text_field :title, :class=>"form-control", :placeholder=>"请输入标题(必填)", :title=>"请输入标题(必填)", :required=>true %>
  </div>
  <div class="form-group">
    <%= f.label "视频链接", :class=>"col-sm-3", :for=>"video_url" %>
    <%= f.text_field :url, :class=>"form-control", :placeholder=>"请输入视频链接(必填)", :title=>"请输入视频链接(必填)", :required=>true %>
  </div>
  <div class="form-group">
    <%= f.label "演讲者", :class=>"col-sm-3", :for=>"video_lecturer" %>
    <%= f.text_field :lecturer, :class=>"form-control", :placeholder=>"请输入演讲者(必填)", :title=>"请输入演讲者(必填)", :required=>true %>
  </div>
  <div class="form-group">
    <%= f.label "描述", :class=>"col-sm-12", :for=>"video_summary" %>
    <div class="wmd-panel">
        <div id="wmd-button-bar"></div>
        <%= f.text_area :summary, :class=>"wmd-input", :id=>"wmd-input" %>
    </div>
    <div class="wmd-panel wmd-preview" id="wmd-preview"></div>
  </div>
  <div class="actions">
    <%= f.submit :class=>"btn btn-success" %>
  </div>
<% end %>

app/views/videos/_recommend.html.erb
<aside class="col-sm-4">
  <section class="wm-recommend">
    <h3 class="page-header">
      <span class="glyphicon glyphicon-plus-sign"></span> 推荐视频
      <a class="wm-quick-link" href="">查看全部</a>
    </h3>
    <div class="row">
      <% @best.each do |recommend| %>
      <figure class="col-xs-6">
        <a class="thumbnail" href="/videos/<%= recommend.id %>.html">
          <img src="<%= recommend.cover %>!medium" alt="" title="<%= recommend.title %>"/>
        </a>
        <figcaption>
          <a href="/videos/<%= recommend.id %>.html" title="<%= recommend.title %>"><%= recommend.title %></a>
        </figcaption>
      </figure>
      <% end %>
    </div>
  </section>
</aside>

app/views/videos/edit.html.erb
<% content_for :head do %>
   <title><%= @video.title %> | 万门大学</title>
<% end %>

<main class="container" role="main">
    <section class="col-sm-8">
        <h1>编辑视频</h1>
        <%= render 'form' %>
        <span class="wm-quick-link">
        <%= link_to '返回', videos_path  %>
        </span>
    </section>
</main>

<% content_for :bottom_script do %>
    <%= render :partial => 'layouts/markdown' %>
<% end %>

app/views/videos/index.html.erb
 <% content_for :head do %>
   <title>视频 | 万门大学</title>
<% end %>

<main class="container" role="main">
  <article class="col-sm-8">
    <section class="wm-gallery">
      <h3 class="page-header">
        <span class="glyphicon glyphicon-star"></span> 精选视频集
        <a class="wm-quick-link" href="/search?list=video&sortby=rate">查看全部</a>
      </h3>
      <div class="row">
        <% @bestVideolist.each do |list|%>
        <figure class="col-sm-4 col-xs-6">
          <a href="/lists/<%= list.id %>.html" class="thumbnail">
            <img src="<%= list.cover.url("medium") %>" alt="<%= list.title %>" title="<%= list.title %>"/>
          </a>
          <figcaption>
            <a href="/lists/<%= list.id %>.html" title="<%= list.title %>"><%= list.title %></a>
          </figcaption>
        </figure>
        <% end %>
      </div>

    </section>
  </article>


  <aside class="col-sm-4">
    <section>
      <h3 class="page-header">
        <span class="glyphicon glyphicon-th-list"></span> 热门视频
        <a class="wm-quick-link" href="/search?type=video&sortby=popularity">查看全部</a>
      </h3>
      <ol class="wm-list-popular">
        <% @popular.each do |video| %>
          <li><a href="/videos/<%=video.id %>"> <%=video.title %></a></li>
        <% end %>
      </ol>
    </section>

    <!--
    <section>
      <h3 class="page-header">
        <span class="glyphicon glyphicon-stats"></span> 热门标签
        <a class="wm-quick-link" href="">查看全部</a>
      </h3>
      <div class="wm-tags-popular">
        【<a class="wm-tag-category" href="">物理</a>】
        <a href="">牛顿力学</a> |
        <a href="">统计物理</a> |
        <a href="">量子场论</a>
      </div>
      <div class="wm-tags-popular">
        【<a class="wm-tag-category" href="">计算机</a>】
        <a href="">编程</a> |
        <a href="">机器学习</a> |
        <a href="">网页设计</a>
      </div>
      <div class="wm-tags-popular">
        【<a class="wm-tag-category" href="">数学</a>】
        <a href="">微积分</a> |
        <a href="">线性代数</a> |
        <a href="">数学物理方程</a>
      </div>
      <div class="wm-tags-popular">
        【<a class="wm-tag-category" href="">外国语</a>】
        <a href="">英语</a> |
        <a href="">法语</a> |
        <a href="">希伯来语</a>
      </div>
      <div class="wm-tags-popular">
        【<a class="wm-tag-category" href="">文学</a>】
        <a href="">中国古典文学</a> |
        <a href="">文学史</a> |
        <a href="">希腊文学</a>
      </div>
    </section>
    -->
  </aside>
</main>

app/views/videos/new.html.erb
<% content_for :head do %>
   <title><%= @video.title %> | 万门大学</title>
<% end %>

<main class="container" role="main">
    <section class="col-sm-8">
        <h1>添加视频</h1>
        <%= render 'form' %>
        <span class="wm-quick-link">
        <%= link_to '返回', videos_path  %>
        </span>
    </section>
</main>

<% content_for :bottom_script do %>
    <%= render :partial => 'layouts/markdown' %>
<% end %>

app/views/videos/show.html.erb
<% content_for :head do %>
   <title><%= @video.title %> | 万门大学</title>
<% end %>

<main class="container" role="main">
  <article class="col-sm-8">
    <h3 class="page-header">
      <span class="wm-title"><%= @video.title %></span>
      <span class="wm-quick-link">
        <% if can? :edit, @video %>
        <%= link_to '修改', edit_video_path(@video) %>  |
        <% end %>
        <%= link_to '返回', videos_path %>
        <% if can? :destroy, @video %>
         | <%= link_to '删除', video_path(@video), method: :delete, data: { confirm: '请确认要删除此视频?'} %>
        <% end %>
      </span>
    </h3>
    <section class="row wm-gallery">
      <figure class="col-sm-4 col-xs-6 wm-show-video">
        <a href="<%= @video.url %>" class="thumbnail">
          <%= image_tag(@video.cover.url("medium")) %>
        </a>
        <figcaption>
          <a href="<%= @video.url %>">观看视频</a>
        </figcaption>
      </figure>
      <div class="col-sm-8 col-xs-6 wm-metadata">
        <span>主讲人</span> <%= @video.lecturer %> <br/>
        <span>学校</span> <br/>
        <span>时长</span> <br/>
        <hr/> 
            <%= render :partial => 'taglinks/taglinks' %>
            <%= render :partial => 'taglinks/form' %>
        <br/>

            <%= render :partial => 'links/links' %>
            <%= render :partial => 'links/form' %>
        <br/>
            <%= render :partial => 'rates/rates' %>
            <%= render :partial => 'rates/form' %>
        <br/>
            <%= render :partial => 'likes/likes' %>
            <%= render :partial => 'likes/form' %>
      </div>
    </section>

    <section class="wm-video">
      <h3>
        <%= @video.title %>
        <button class="close" type="button">
          <span class="glyphicon glyphicon-remove-circle"></span>
        </button>
      </h3>
      <iframe src="http://player.youku.com/"></iframe>
    </section>

    <hr/>

    <section class="wm-indent">
      <%=raw Kramdown::Document.new(@video.summary).to_html%>
    </section>
    <hr/>
    <%= render :partial => 'comments/shares' %>  
    <%= render :partial => 'comments/comments' %>
    <hr/>
    <%= render :partial => 'comments/form' %>
  </article>
  <%= render :partial => 'videos/recommend' %>
</main>

<% content_for :bottom_script do %>
  <%= render :partial => 'layouts/markdown' %>
  <%= render :partial => 'layouts/raty' %>
  <%= render :partial => 'layouts/rails' %>
<% end %>